install.packages("kableExtra")
install.packages("dplyr")
install.packages("easyPubMed")
library(kableExtra)
library(dplyr)
library(easyPubMed)
my_query <- readline(prompt="Enter keywords: ")
#The common window would ask for your input, enter keywords here.  
my_query <- get_pubmed_ids(my_query)
my_abstracts_xml <- fetch_pubmed_data(my_query)
all_xml <- articles_to_list(my_abstracts_xml)
final_df <- do.call(rbind, lapply(all_xml, article_to_df, max_chars = -1, getAuthors = TRUE))
write.csv(final_df, file=file.choose())
write.csv(final_df, file="/cloud/project/file.csv")

